package dev.lanthoor.spendly.architecture

import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.Optional
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction
import java.io.File

abstract class GenerateArchitectureBoundaryBaselineTask : DefaultTask() {
    @get:Input
    abstract val sourceRoot: Property<String>

    @get:Input
    abstract val packagePrefix: Property<String>

    @get:Input
    abstract val featureRootPackage: Property<String>

    @get:OutputFile
    abstract val baselineFile: RegularFileProperty

    @TaskAction
    fun generate() {
        val config = ArchitectureRuleConfig(
            sourceRoot = sourceRoot.get(),
            baselineFile = project.rootProject.projectDir
                .toPath()
                .relativize(baselineFile.get().asFile.toPath())
                .toString(),
            packagePrefix = packagePrefix.get(),
            featureRootPackage = featureRootPackage.get(),
        )

        val scanner = ArchitectureBoundaryScanner(config)
        val violations = scanner.scan(project.rootProject.projectDir)
        val entries = violations.map { it.baselineEntry() }

        val output = buildString {
            appendLine("# Architecture boundary baseline")
            appendLine("# Generated by :generateArchitectureBoundaryBaseline")
            appendLine("# Format: RULE|FILE|LINE|MESSAGE")
            appendLine()
            entries.forEach { appendLine(it) }
        }

        val file = baselineFile.get().asFile
        file.parentFile.mkdirs()
        file.writeText(output)

        logger.lifecycle("Wrote ${entries.size} baseline violations to ${file.path}")
    }
}

abstract class CheckArchitectureBoundariesTask : DefaultTask() {
    @get:Input
    abstract val sourceRoot: Property<String>

    @get:Input
    abstract val packagePrefix: Property<String>

    @get:Input
    abstract val featureRootPackage: Property<String>

    @get:InputFile
    @get:Optional
    abstract val baselineFile: RegularFileProperty

    @TaskAction
    fun check() {
        val baseDir = project.rootProject.projectDir
        val baseline = baselineFile.orNull?.asFile
        if (baseline == null || !baseline.exists()) {
            throw GradleException(
                "Baseline file is missing. Run './gradlew generateArchitectureBoundaryBaseline' first."
            )
        }

        val config = ArchitectureRuleConfig(
            sourceRoot = sourceRoot.get(),
            baselineFile = baseDir.toPath().relativize(baseline.toPath()).toString(),
            packagePrefix = packagePrefix.get(),
            featureRootPackage = featureRootPackage.get(),
        )
        val scanner = ArchitectureBoundaryScanner(config)
        val current = scanner.scan(baseDir)
        val currentEntries = current.map { it.baselineEntry() }.toSet()
        val baselineEntries = readBaselineEntries(baseline)

        val newViolations = currentEntries - baselineEntries
        if (newViolations.isNotEmpty()) {
            val details = newViolations.sorted().joinToString(separator = "\n") { " - $it" }
            throw GradleException(
                "Architecture boundary violations introduced (${newViolations.size}):\n$details"
            )
        }

        logger.lifecycle(
            "Architecture boundaries check passed. " +
                "Current violations: ${currentEntries.size}, baseline: ${baselineEntries.size}."
        )
    }

    private fun readBaselineEntries(file: File): Set<String> = file
        .readLines()
        .asSequence()
        .map { it.trim() }
        .filter { it.isNotEmpty() }
        .filterNot { it.startsWith("#") }
        .toSet()
}
